// shared-core/toast-pool.mjs — preset toast messages

export const POOL = [
  { cat: 'slack', title: '이수민', body: '방금 공유한 거 한번 봐주실 수 있어요?', target: 'busy/messenger.html' },
  { cat: 'slack', title: '#growth', body: 'kpi-refresh 끝났어요. 링크 첨부합니다.', target: 'busy/messenger.html' },
  { cat: 'slack', title: '박지훈', body: '리뷰 요청드려요. 급한 건 아니고요.', target: 'busy/messenger.html' },
  { cat: 'slack', title: '@everyone', body: '금요일 회식 장소 투표 ▸', target: 'busy/messenger.html' },
  { cat: 'slack', title: '#alerts', body: '🔴 prod-eu-west p99 latency 800ms 초과', target: '열일하는중.html' },
  { cat: 'slack', title: '#eng-design', body: 'v2 시안 올렸어요. 피드백 부탁!', target: 'busy/design.html' },
  { cat: 'slack', title: '한서연', body: '내일 10시 1:1 가능해요?', target: 'busy/calendar.html' },
  { cat: 'slack', title: '@channel', body: '배포 중이에요. 머지 잠시 보류해주세요.', target: 'busy/devops.html' },
  { cat: 'mail', title: 'CEO 사무국', body: '금주 주간 보고 취합 요청드립니다.', target: 'busy/email.html' },
  { cat: 'mail', title: '한국어뉴스', body: '[속보] 환율 1,410원 돌파', target: 'busy/email.html' },
  { cat: 'mail', title: 'AWS Health', body: 'Scheduled RDS maintenance', target: 'busy/email.html' },
  { cat: 'mail', title: '김과장', body: 'RE: Q2 실적 분석 건 (회신 요망)', target: 'busy/email.html' },
  { cat: 'mail', title: 'GitHub', body: '[PR #1423] review requested from you', target: 'busy/issuetracker.html' },
  { cat: 'mail', title: 'Figma', body: 'design-review commented on your file', target: 'busy/design.html' },
  { cat: 'mail', title: 'Calendar', body: '14:00 · CTO 1:1 · 시작 15분 전', target: 'busy/calendar.html' },
  { cat: 'mail', title: 'Zoom', body: '참여 대기 중 · 팀 스탠드업', target: null },
  { cat: 'cal', title: '회의 알림', body: '15:00 스프린트 플래닝 (30분 후)', target: 'busy/calendar.html' },
  { cat: 'cal', title: '일정 추가', body: '이수민님이 새 일정을 공유했습니다', target: 'busy/calendar.html' },
  { cat: 'cal', title: '집중 시간', body: '47분 남음 · 알림 억제 중', target: null },
  { cat: 'sys', title: '저장 완료', body: 'Q2_실적분석_v14_최종_수정본_진짜최종.xlsx', target: null },
  { cat: 'sys', title: '업데이트 가능', body: 'Slack 4.45.0 → 4.45.1', target: null },
  { cat: 'sys', title: '백업', body: 'Time Machine 백업 완료 (2.3 GB)', target: null },
  { cat: 'sys', title: '보안 경고', body: '새 기기에서 로그인이 감지되었습니다', target: null },
  { cat: 'sys', title: 'VPN', body: 'corp-gw-seoul 연결됨', target: null },
  { cat: 'sys', title: '클립보드', body: '방금 복사 · 256자', target: null },
  { cat: 'slack', title: '이재민', body: '이거 RCA에 넣을까요?', target: 'busy/messenger.html' },
  { cat: 'slack', title: '#product', body: '로드맵 Q3 초안 공유드립니다', target: 'busy/ppt.html' },
  { cat: 'mail', title: 'Linear', body: 'GROWTH-1423 moved to In Review', target: 'busy/issuetracker.html' },
  { cat: 'mail', title: 'PagerDuty', body: '[RESOLVED] db-primary high CPU', target: 'busy/devops.html' },
  { cat: 'cal', title: '점심 알림', body: '12:30 · 팀 점심 · 1층 카페', target: 'busy/calendar.html' },
  { cat: 'sys', title: 'Oracle DW', body: '12,482행 가져오는 중...', target: null },
  { cat: 'slack', title: '송민지', body: '잠깐 콜 가능해요? 5분만요', target: 'busy/messenger.html' },
  { cat: 'slack', title: '#platform', body: 'k8s 1.29 업그레이드 완료', target: 'busy/devops.html' },
  { cat: 'mail', title: 'LinkedIn', body: '3명이 내 프로필을 조회했습니다', target: null },
  { cat: 'mail', title: '사내공지', body: '[필독] 4월 정기 보안 교육', target: 'busy/email.html' },
  { cat: 'cal', title: '회의 종료', body: 'KPI 리뷰 · 끝났습니다', target: null },
  { cat: 'sys', title: 'SAP', body: '월마감 처리 배치 시작 · 진행 23%', target: 'busy/erp.html' },
  { cat: 'sys', title: 'Docker', body: '이미지 빌드 완료 · api-v2.7 (1.2 GB)', target: 'busy/devops.html' },
  { cat: 'slack', title: '최수영', body: '커피 한잔 하실래요?', target: null },
  { cat: 'mail', title: 'FedEx', body: '배송 예정 · 오늘 오후', target: null },
  { cat: 'cal', title: '반복 일정', body: '매주 금 17:00 · 회고', target: 'busy/calendar.html' },
  { cat: 'sys', title: '디스크 공간', body: '시스템 드라이브 여유 공간 15% 미만', target: null },
  { cat: 'slack', title: '#incidents', body: '🟠 orders-api p95 급등', target: '열일하는중.html' },
  { cat: 'slack', title: '#finance', body: '4월 정산 완료, 확인 부탁드려요', target: 'busy/email.html' },
  { cat: 'mail', title: 'AWS Billing', body: '$312.47 · 전월 대비 +8%', target: null },
  { cat: 'sys', title: 'VS Code', body: '워크스페이스 복구 완료', target: null },
  { cat: 'slack', title: '@DM 김PM', body: '스펙 초안 확인했어요. 의견 드릴게요', target: 'busy/messenger.html' },
  { cat: 'mail', title: 'Bloomberg', body: 'KOSPI -1.2% · 외국인 순매도 지속', target: 'busy/hts.html' },
  { cat: 'cal', title: '1:1 준비', body: '14:30 CTO 1:1 · 노트 열기', target: 'busy/notebook.html' },
  { cat: 'sys', title: '네트워크', body: 'VPN 연결이 재설정되었습니다', target: null },
  { cat: 'slack', title: '#design', body: '로고 가이드 v3 배포', target: 'busy/design.html' },
  { cat: 'mail', title: 'Zendesk', body: '신규 티켓 #8842 · 응답 대기 중', target: 'busy/issuetracker.html' },
  { cat: 'cal', title: '오늘의 할 일', body: '3개 완료 · 5개 남음', target: null },
  { cat: 'sys', title: '압축 완료', body: 'render_scene_04.zip (2.1 GB)', target: 'busy/3dmodel.html' },
  { cat: 'slack', title: '박대표', body: '이번주 성과 요약 부탁드려요', target: 'busy/ppt.html' },
  { cat: 'mail', title: 'Stripe', body: '결제 실패 1건 · 수동 처리 필요', target: null },
  { cat: 'sys', title: '자동 저장', body: 'main.tex 저장됨 · 오후 3:47', target: 'busy/latex.html' },
  { cat: 'slack', title: '김팀장', body: '내일 오전 30분만 시간 돼요?', target: 'busy/calendar.html' },
  { cat: 'mail', title: 'DHL Express', body: '배송 지연 안내 · 익일 재시도', target: null },
  { cat: 'cal', title: '스탠드업', body: '10:00 · 2분 전 시작', target: null },
];

export function randomToast() {
  return POOL[Math.floor(Math.random() * POOL.length)];
}
